### ISSUE TITLE
Training data from paper

### ISSUE THREAD

**Issue by Hoeze** [BennyStrobes/Watershed#1]
Hi, I'd like to ask where one can find the GTEx summary statistics you used to train WATERSHED and how to reproduce that. 
In your "Diverse transcriptomic signatures across human tissues identify functional rare genetic variation" paper I could find the feature types (suppl. table 4) but not the actual dataset.
Thanks in advance!

**Comment by BennyStrobes** [comment]
Hi. Unfortunately, we are using rare variant calls instead of summary statistics to train Watershed. Meaning, I am unable to share the actual input file because it contains patient-protected information.
